// Date: 9/28/2013 2:36:51 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package assets.bigmod.textures.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Barrow extends ModelBase
{
    //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;

    public Barrow()
    {
        textureWidth = 128;
        textureHeight = 64;
        Shape1 = new ModelRenderer(this, 0, 32);
        Shape1.addBox(0F, 0F, 0F, 11, 3, 11);
        Shape1.setRotationPoint(-5F, 21F, -5F);
        Shape1.setTextureSize(128, 64);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);
        Shape2 = new ModelRenderer(this, 0, 8);
        Shape2.addBox(0.5F, 0F, -0.5F, 8, 2, 8);
        Shape2.setRotationPoint(-4F, 16F, -3F);
        Shape2.setTextureSize(128, 64);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, 0F, 0F);
        Shape3 = new ModelRenderer(this, 0, 19);
        Shape3.addBox(-0.5F, 0F, -0.5F, 10, 3, 10);
        Shape3.setRotationPoint(-4F, 18F, -4F);
        Shape3.setTextureSize(128, 64);
        Shape3.mirror = true;
        setRotation(Shape3, 0F, 0F, 0F);
        Shape4 = new ModelRenderer(this, 45, 0);
        Shape4.addBox(0F, 0F, 0F, 3, 3, 2);
        Shape4.setRotationPoint(-1F, 20F, -6F);
        Shape4.setTextureSize(128, 64);
        Shape4.mirror = true;
        setRotation(Shape4, 0F, 0F, 0F);
        Shape5 = new ModelRenderer(this, 0, 0);
        Shape5.addBox(0F, 0F, 0F, 1, 1, 1);
        Shape5.setRotationPoint(-3F, 19F, -5F);
        Shape5.setTextureSize(128, 64);
        Shape5.mirror = true;
        setRotation(Shape5, 0F, 0F, 0F);
        Shape6 = new ModelRenderer(this, 0, 0);
        Shape6.addBox(0F, 0F, 0F, 1, 1, 1);
        Shape6.setRotationPoint(3F, 19F, -5F);
        Shape6.setTextureSize(128, 64);
        Shape6.mirror = true;
        setRotation(Shape6, 0F, 0F, 0F);
        Shape7 = new ModelRenderer(this, 80, 3);
        Shape7.addBox(1F, 0F, 0F, 3, 1, 3);
        Shape7.setRotationPoint(-8F, 21F, 1F);
        Shape7.setTextureSize(128, 64);
        Shape7.mirror = true;
        setRotation(Shape7, 0F, 0.5934119F, 0F);
        Shape8 = new ModelRenderer(this, 80, 3);
        Shape8.addBox(0F, 0F, 0F, 3, 1, 3);
        Shape8.setRotationPoint(6F, 21F, -1F);
        Shape8.setTextureSize(128, 64);
        Shape8.mirror = true;
        setRotation(Shape8, 0F, -0.5948578F, 0F);
        Shape9 = new ModelRenderer(this, 43, 12);
        Shape9.addBox(0F, 0F, 0F, 3, 1, 3);
        Shape9.setRotationPoint(-1F, 22F, 6F);
        Shape9.setTextureSize(128, 64);
        Shape9.mirror = true;
        setRotation(Shape9, 0.5948578F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Shape1.render(f5);
        Shape2.render(f5);
        Shape3.render(f5);
        Shape4.render(f5);
        Shape5.render(f5);
        Shape6.render(f5);
        Shape7.render(f5);
        Shape8.render(f5);
        Shape9.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }


}
