// Date: 12/7/2013 1:18:04 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.bigmod.textures.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class bblock extends ModelBase
{
  //fields
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape9;
    ModelRenderer Shape12;
    ModelRenderer Shape14;
  
  public bblock()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      Shape10 = new ModelRenderer(this, 72, 32);
      Shape10.addBox(0F, 0F, 0F, 14, 1, 14);
      Shape10.setRotationPoint(-7F, 23F, -7F);
      Shape10.setTextureSize(64, 32);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 0, 64);
      Shape11.addBox(0F, 0F, 0F, 12, 14, 12);
      Shape11.setRotationPoint(-6F, 9F, -6F);
      Shape11.setTextureSize(64, 32);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 64, 47);
      Shape9.addBox(0F, 0.5F, 0F, 16, 1, 16);
      Shape9.setRotationPoint(-8F, 23F, -8F);
      Shape9.setTextureSize(64, 32);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 64, 47);
      Shape12.addBox(0F, 0F, 0F, 16, 1, 16);
      Shape12.setRotationPoint(-8F, 8F, -8F);
      Shape12.setTextureSize(64, 32);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 0F);
      Shape14 = new ModelRenderer(this, 72, 32);
      Shape14.addBox(0F, 0F, 0F, 14, 1, 14);
      Shape14.setRotationPoint(-7F, 9F, -7F);
      Shape14.setTextureSize(64, 32);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape10.render(f5);
    Shape11.render(f5);
    Shape9.render(f5);
    Shape12.render(f5);
    Shape14.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
