// Date: 12/20/2013 8:33:00 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.bigmod.textures.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class fossilizer extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
  
  public fossilizer()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0.1F, 0F, 1F, 1, 32, 7);
      Shape1.setRotationPoint(2F, -8F, -8F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 1.003826F, 0F);
      Shape2 = new ModelRenderer(this, 0, 0);
      Shape2.addBox(0.44F, 0F, 0F, 2, 32, 7);
      Shape2.setRotationPoint(-3F, -8F, -6F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 1.570796F, 0F);
      Shape3 = new ModelRenderer(this, 70, 0);
      Shape3.addBox(1F, 0F, 0F, 1, 32, 11);
      Shape3.setRotationPoint(10F, -8F, 7F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 3.141593F, 0F);
      Shape4 = new ModelRenderer(this, 0, 0);
      Shape4.addBox(-0.5F, 0F, 0F, 1, 32, 8);
      Shape4.setRotationPoint(-2F, -8F, -8F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, -1.003826F, 0F);
      Shape5 = new ModelRenderer(this, 70, 0);
      Shape5.addBox(0.5F, 0F, 0F, 1, 32, 11);
      Shape5.setRotationPoint(-8F, -8F, 7F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 3.141593F, 0F);
      Shape6 = new ModelRenderer(this, 86, 70);
      Shape6.addBox(-0.7F, 0F, 0F, 19, 32, 1);
      Shape6.setRotationPoint(-9F, -8F, 7F);
      Shape6.setTextureSize(64, 32);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 0, 70);
      Shape7.addBox(0F, 0F, 0F, 18, 3, 18);
      Shape7.setRotationPoint(-9F, -11F, -9F);
      Shape7.setTextureSize(256, 128);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
