// Date: 9/29/2013 12:43:26 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package assets.bigmod.textures.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Geoduck extends ModelBase
{
    //fields
    ModelRenderer penis;
    ModelRenderer body;
    ModelRenderer tip;
    ModelRenderer body_top;

    public Geoduck()
    {
        textureWidth = 64;
        textureHeight = 32;
        penis = new ModelRenderer(this, 0, 2);
        penis.addBox(0F, 0F, 0F, 1, 1, 8);
        penis.setRotationPoint(2F, 23F, -5F);
        penis.setTextureSize(64, 32);
        penis.mirror = true;
        setRotation(penis, 0F, -0.3717861F, 0F);
        body = new ModelRenderer(this, -1, 11);
        body.addBox(0F, 0F, 0F, 3, 1, 4);
        body.setRotationPoint(-1F, 23F, 0F);
        body.setTextureSize(64, 32);
        body.mirror = true;
        setRotation(body, 0F, 0F, 0F);
        tip = new ModelRenderer(this, 0, 0);
        tip.addBox(0.5F, 0F, 0.7F, 1, 1, 1);
        tip.setRotationPoint(2F, 23F, -6F);
        tip.setTextureSize(64, 32);
        tip.mirror = true;
        setRotation(tip, 0F, -0.3703403F, 0F);
        body_top = new ModelRenderer(this, 0, 16);
        body_top.addBox(0.5F, 0F, 0.5F, 2, 1, 3);
        body_top.setRotationPoint(-1F, 22F, 0F);
        body_top.setTextureSize(64, 32);
        body_top.mirror = true;
        setRotation(body_top, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        penis.render(f5);
        body.render(f5);
        tip.render(f5);
        body_top.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }
}
