// Date: 12/7/2013 1:56:56 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.bigmod.textures.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelDubGun extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape17;
    ModelRenderer Shape18;
    ModelRenderer Shape19;
    ModelRenderer Shape20;
    ModelRenderer Shape21;
    ModelRenderer Shape22;
    ModelRenderer Shape23;
    ModelRenderer Shape24;
    ModelRenderer Shape25;
    ModelRenderer Shape26;
    ModelRenderer Shape27;
    ModelRenderer Shape28;
    ModelRenderer Shape29;
    ModelRenderer Shape30;
    ModelRenderer Shape31;
    ModelRenderer Shape32;
    ModelRenderer Shape33;
    ModelRenderer Shape34;
    ModelRenderer Shape35;
  
  public ModelDubGun()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Shape1 = new ModelRenderer(this, 42, 23);
      Shape1.addBox(-1F, -1F, 12F, 2, 2, 4);
      Shape1.setRotationPoint(0F, 0F, 0F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 8, 18);
      Shape2.addBox(-0.5F, -5.5F, 10F, 1, 1, 1);
      Shape2.setRotationPoint(0F, 0F, 0F);
      Shape2.setTextureSize(128, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 86, 47);
      Shape3.addBox(2F, 0F, -23.5F, 1, 1, 5);
      Shape3.setRotationPoint(0F, 0F, 0F);
      Shape3.setTextureSize(128, 64);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 28, 22);
      Shape4.addBox(-3F, -3F, 11F, 6, 6, 1);
      Shape4.setRotationPoint(0F, 0F, 0F);
      Shape4.setTextureSize(128, 64);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 28, 29);
      Shape5.addBox(-3F, -3F, -4.5F, 6, 6, 2);
      Shape5.setRotationPoint(0F, 0F, 0F);
      Shape5.setTextureSize(128, 64);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 26, 0);
      Shape6.addBox(-2F, -0.5F, -51.5F, 4, 10, 2);
      Shape6.setRotationPoint(0F, 0F, 0F);
      Shape6.setTextureSize(128, 64);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 0, 44);
      Shape7.addBox(-1.473333F, -4F, -51F, 3, 6, 14);
      Shape7.setRotationPoint(0F, 0F, 0F);
      Shape7.setTextureSize(128, 64);
      Shape7.mirror = true;
      setRotation(Shape7, 0.1396263F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 14, 18);
      Shape8.addBox(4F, -2F, -14.5F, 3, 2, 1);
      Shape8.setRotationPoint(0F, 0F, 0F);
      Shape8.setTextureSize(128, 64);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0.1570796F, 0F);
      Shape9 = new ModelRenderer(this, 70, 18);
      Shape9.addBox(-2F, -8.5F, -15.5F, 4, 4, 1);
      Shape9.setRotationPoint(0F, 0F, 0F);
      Shape9.setTextureSize(128, 64);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 86, 47);
      Shape10.addBox(-3F, 0F, -23.5F, 1, 1, 5);
      Shape10.setRotationPoint(0F, 0F, 0F);
      Shape10.setTextureSize(128, 64);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 40, 52);
      Shape11.addBox(-5F, 4F, -18.5F, 10, 7, 5);
      Shape11.setRotationPoint(0F, 0F, 0F);
      Shape11.setTextureSize(128, 64);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 70, 53);
      Shape12.addBox(-2F, 0F, -23.5F, 4, 1, 10);
      Shape12.setRotationPoint(0F, 0F, 0F);
      Shape12.setTextureSize(128, 64);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 0F);
      Shape13 = new ModelRenderer(this, 70, 53);
      Shape13.addBox(-2F, -2.5F, -13.5F, 4, 6, 1);
      Shape13.setRotationPoint(0F, 0F, 0F);
      Shape13.setTextureSize(128, 64);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0F, 0F);
      Shape14 = new ModelRenderer(this, 0, 12);
      Shape14.addBox(-6.5F, -0.5F, -8.5F, 4, 1, 1);
      Shape14.setRotationPoint(0F, 0F, 0F);
      Shape14.setTextureSize(128, 64);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0.0698132F, 0.6806784F);
      Shape15 = new ModelRenderer(this, 0, 44);
      Shape15.addBox(-1.5F, -2F, -28.5F, 3, 5, 4);
      Shape15.setRotationPoint(0F, 0F, 0F);
      Shape15.setTextureSize(128, 64);
      Shape15.mirror = true;
      setRotation(Shape15, 0F, 0F, 0F);
      Shape16 = new ModelRenderer(this, 0, 44);
      Shape16.addBox(-1.5F, -11.5F, -32F, 3, 5, 6);
      Shape16.setRotationPoint(0F, 0F, 0F);
      Shape16.setTextureSize(128, 64);
      Shape16.mirror = true;
      setRotation(Shape16, 0.3490659F, 0F, 0F);
      Shape17 = new ModelRenderer(this, 0, 44);
      Shape17.addBox(-1.473333F, -18.3F, -36F, 3, 5, 8);
      Shape17.setRotationPoint(0F, 0F, 0F);
      Shape17.setTextureSize(128, 64);
      Shape17.mirror = true;
      setRotation(Shape17, 0.5794493F, 0F, 0F);
      Shape18 = new ModelRenderer(this, 0, 44);
      Shape18.addBox(-1.473333F, 0F, -51F, 3, 3, 17);
      Shape18.setRotationPoint(0F, 0F, 0F);
      Shape18.setTextureSize(128, 64);
      Shape18.mirror = true;
      setRotation(Shape18, 0F, 0F, 0F);
      Shape19 = new ModelRenderer(this, 70, 53);
      Shape19.addBox(-2F, -2.5F, -24.5F, 4, 6, 1);
      Shape19.setRotationPoint(0F, 0F, 0F);
      Shape19.setTextureSize(128, 64);
      Shape19.mirror = true;
      setRotation(Shape19, 0F, 0F, 0F);
      Shape20 = new ModelRenderer(this, 70, 45);
      Shape20.addBox(-1F, -2F, -19.5F, 2, 2, 6);
      Shape20.setRotationPoint(0F, 0F, 0F);
      Shape20.setTextureSize(128, 64);
      Shape20.mirror = true;
      setRotation(Shape20, 0F, 0F, 0F);
      Shape21 = new ModelRenderer(this, 18, 21);
      Shape21.addBox(3F, -1.5F, -14.5F, 1, 1, 1);
      Shape21.setRotationPoint(0F, 0F, 0F);
      Shape21.setTextureSize(128, 64);
      Shape21.mirror = true;
      setRotation(Shape21, 0F, 0.1570796F, 0F);
      Shape22 = new ModelRenderer(this, 70, 37);
      Shape22.addBox(-2F, -2.5F, -23.5F, 4, 3, 5);
      Shape22.setRotationPoint(0F, 0F, 0F);
      Shape22.setTextureSize(128, 64);
      Shape22.mirror = true;
      setRotation(Shape22, 0F, 0F, 0F);
      Shape23 = new ModelRenderer(this, 70, 31);
      Shape23.addBox(-1.5F, -3.5F, -23.5F, 3, 1, 5);
      Shape23.setRotationPoint(0F, 0F, 0F);
      Shape23.setTextureSize(128, 64);
      Shape23.mirror = true;
      setRotation(Shape23, 0F, 0F, 0F);
      Shape24 = new ModelRenderer(this, 70, 23);
      Shape24.addBox(-1F, -4.5F, -21.5F, 2, 1, 7);
      Shape24.setRotationPoint(0F, 0F, 0F);
      Shape24.setTextureSize(128, 64);
      Shape24.mirror = true;
      setRotation(Shape24, 0F, 0F, 0F);
      Shape25 = new ModelRenderer(this, 0, 23);
      Shape25.addBox(-3.5F, -3.5F, -3F, 7, 7, 14);
      Shape25.setRotationPoint(0F, 0F, 0F);
      Shape25.setTextureSize(128, 64);
      Shape25.mirror = true;
      setRotation(Shape25, 0F, 0F, 0F);
      Shape26 = new ModelRenderer(this, 8, 18);
      Shape26.addBox(-0.5F, -4.5F, 9F, 1, 1, 2);
      Shape26.setRotationPoint(0F, 0F, 0F);
      Shape26.setTextureSize(128, 64);
      Shape26.mirror = true;
      setRotation(Shape26, 0F, 0F, 0F);
      Shape27 = new ModelRenderer(this, 0, 46);
      Shape27.addBox(-1.5F, 1F, -23.5F, 3, 2, 10);
      Shape27.setRotationPoint(0F, 0F, 0F);
      Shape27.setTextureSize(128, 64);
      Shape27.mirror = true;
      setRotation(Shape27, 0F, 0F, 0F);
      Shape28 = new ModelRenderer(this, 54, 10);
      Shape28.addBox(0F, 3.5F, -29.5F, 0, 4, 8);
      Shape28.setRotationPoint(0F, 0F, 0F);
      Shape28.setTextureSize(128, 64);
      Shape28.mirror = true;
      setRotation(Shape28, 0F, 0F, 0F);
      Shape29 = new ModelRenderer(this, 40, 46);
      Shape29.addBox(-1F, 3F, -18.5F, 2, 1, 5);
      Shape29.setRotationPoint(0F, 0F, 0F);
      Shape29.setTextureSize(128, 64);
      Shape29.mirror = true;
      setRotation(Shape29, 0F, 0F, 0F);
      Shape30 = new ModelRenderer(this, 98, 42);
      Shape30.addBox(-1F, 2.5F, -29.5F, 2, 1, 8);
      Shape30.setRotationPoint(0F, 0F, 0F);
      Shape30.setTextureSize(128, 64);
      Shape30.mirror = true;
      setRotation(Shape30, 0F, 0F, 0F);
      Shape31 = new ModelRenderer(this, 98, 51);
      Shape31.addBox(-1.5F, -2F, -12.5F, 3, 5, 8);
      Shape31.setRotationPoint(0F, 0F, 0F);
      Shape31.setTextureSize(128, 64);
      Shape31.mirror = true;
      setRotation(Shape31, 0F, 0F, 0F);
      Shape32 = new ModelRenderer(this, 0, 17);
      Shape32.addBox(-3.5F, -2F, -11.5F, 2, 2, 2);
      Shape32.setRotationPoint(0F, 0F, 0F);
      Shape32.setTextureSize(128, 64);
      Shape32.mirror = true;
      setRotation(Shape32, 0F, 0F, 0F);
      Shape33 = new ModelRenderer(this, 0, 44);
      Shape33.addBox(-8F, -1F, -16F, 2, 2, 7);
      Shape33.setRotationPoint(0F, 0F, 0F);
      Shape33.setTextureSize(128, 64);
      Shape33.mirror = true;
      setRotation(Shape33, 0F, 0.0698132F, 0.6806784F);
      Shape34 = new ModelRenderer(this, 0, 12);
      Shape34.addBox(-2.5F, -0.5F, -11.5F, 1, 1, 4);
      Shape34.setRotationPoint(0F, 0F, 0F);
      Shape34.setTextureSize(128, 64);
      Shape34.mirror = true;
      setRotation(Shape34, 0F, 0.0698132F, 0.6806784F);
      Shape35 = new ModelRenderer(this, 0, 12);
      Shape35.addBox(-7.5F, -0.5F, -9.5F, 1, 1, 2);
      Shape35.setRotationPoint(0F, 0F, 0F);
      Shape35.setTextureSize(128, 64);
      Shape35.mirror = true;
      setRotation(Shape35, 0F, 0.0698132F, 0.6806784F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
    Shape13.render(f5);
    Shape14.render(f5);
    Shape15.render(f5);
    Shape16.render(f5);
    Shape17.render(f5);
    Shape18.render(f5);
    Shape19.render(f5);
    Shape20.render(f5);
    Shape21.render(f5);
    Shape22.render(f5);
    Shape23.render(f5);
    Shape24.render(f5);
    Shape25.render(f5);
    Shape26.render(f5);
    Shape27.render(f5);
    Shape28.render(f5);
    Shape29.render(f5);
    Shape30.render(f5);
    Shape31.render(f5);
    Shape32.render(f5);
    Shape33.render(f5);
    Shape34.render(f5);
    Shape35.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
