// Date: 12/21/2013 1:41:05 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.bigmod.textures.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class newfossilizer extends ModelBase
{
  //fields
    ModelRenderer Top;
    ModelRenderer Core;
    ModelRenderer Base;
  
  public newfossilizer()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Top = new ModelRenderer(this, 64, 46);
      Top.addBox(-6F, -10F, -6F, 12, 2, 12);
      Top.setRotationPoint(0F, 19F, 0F);
      Top.setTextureSize(128, 64);
      Top.mirror = true;
      setRotation(Top, 0F, 0F, 0F);
      Core = new ModelRenderer(this, 26, 15);
      Core.addBox(-1F, -11F, -1F, 2, 14, 2);
      Core.setRotationPoint(0F, 19F, 0F);
      Core.setTextureSize(128, 64);
      Core.mirror = true;
      setRotation(Core, 0F, 0.7853982F, 0F);
      Base = new ModelRenderer(this, 0, 46);
      Base.addBox(-8F, -2F, -8F, 16, 2, 16);
      Base.setRotationPoint(0F, 24F, 0F);
      Base.setTextureSize(128, 64);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Top.render(f5);
    Core.render(f5);
    Base.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
