// Date: 9/27/2013 6:09:13 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package assets.bigmod.textures.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Seaweed extends ModelBase
{
    //fields
    ModelRenderer Sprout;
    ModelRenderer Back;
    ModelRenderer BackBranch;
    ModelRenderer RightBranch;
    ModelRenderer Right;
    ModelRenderer left_brainch;
    ModelRenderer left;
    ModelRenderer ehh_branch;
    ModelRenderer ehhhh;

    public Seaweed()
    {
        textureWidth = 64;
        textureHeight = 32;
        Sprout = new ModelRenderer(this, 10, 0);
        Sprout.addBox(0F, 0F, 0F, 1, 24, 1);
        Sprout.setRotationPoint(0F, 0F, 0F);
        Sprout.setTextureSize(64, 32);
        Sprout.mirror = true;
        setRotation(Sprout, 0F, 0F, 0F);
        Back = new ModelRenderer(this, 0, 0);
        Back.addBox(0F, 0F, 0F, 1, 13, 1);
        Back.setRotationPoint(0F, 3F, 5F);
        Back.setTextureSize(64, 32);
        Back.mirror = true;
        setRotation(Back, -0.0743572F, -0.0743572F, 0F);
        BackBranch = new ModelRenderer(this, 0, 17);
        BackBranch.addBox(0F, 0F, 0F, 1, 1, 4);
        BackBranch.setRotationPoint(0F, 14F, 1F);
        BackBranch.setTextureSize(64, 32);
        BackBranch.mirror = true;
        setRotation(BackBranch, -0.3346075F, -0.1487144F, -0.1487144F);
        RightBranch = new ModelRenderer(this, 0, 22);
        RightBranch.addBox(0F, 0F, 0F, 1, 1, 4);
        RightBranch.setRotationPoint(0F, 18F, -3F);
        RightBranch.setTextureSize(64, 32);
        RightBranch.mirror = true;
        setRotation(RightBranch, -0.4089647F, 0F, 0F);
        Right = new ModelRenderer(this, 4, 0);
        Right.addBox(0F, 0F, 0F, 1, 16, 1);
        Right.setRotationPoint(0F, 3F, -4F);
        Right.setTextureSize(64, 32);
        Right.mirror = true;
        setRotation(Right, 0.0371786F, 0F, 0F);
        left_brainch = new ModelRenderer(this, 18, 3);
        left_brainch.addBox(0F, 0F, 0F, 4, 1, 1);
        left_brainch.setRotationPoint(1F, 10F, 0F);
        left_brainch.setTextureSize(64, 32);
        left_brainch.mirror = true;
        setRotation(left_brainch, 0F, -0.0068161F, -0.1858931F);
        left = new ModelRenderer(this, 14, 11);
        left.addBox(0F, 0F, 0F, 1, 9, 1);
        left.setRotationPoint(4F, 1F, 0F);
        left.setTextureSize(64, 32);
        left.mirror = true;
        setRotation(left, 0F, 0F, 0F);
        ehh_branch = new ModelRenderer(this, 18, 0);
        ehh_branch.addBox(0F, 0F, 0F, 3, 1, 1);
        ehh_branch.setRotationPoint(-3F, 11F, 0F);
        ehh_branch.setTextureSize(64, 32);
        ehh_branch.mirror = true;
        setRotation(ehh_branch, 0F, 0F, 0.2602503F);
        ehhhh = new ModelRenderer(this, 14, 0);
        ehhhh.addBox(0F, 0F, 0F, 1, 8, 1);
        ehhhh.setRotationPoint(-3F, 4F, 0F);
        ehhhh.setTextureSize(64, 32);
        ehhhh.mirror = true;
        setRotation(ehhhh, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Sprout.render(f5);
        Back.render(f5);
        BackBranch.render(f5);
        RightBranch.render(f5);
        Right.render(f5);
        left_brainch.render(f5);
        left.render(f5);
        ehh_branch.render(f5);
        ehhhh.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }
}
