// Date: 12/22/2013 1:32:07 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.bigmod.textures.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class StandOrb extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Orb_of_doom;
  
  public StandOrb()
  {
    textureWidth = 1024;
    textureHeight = 512;
    
      Shape1 = new ModelRenderer(this, 0, 500);
      Shape1.addBox(0.5F, 0F, -0.5F, 3, 1, 3);
      Shape1.setRotationPoint(-2F, 23F, -1F);
      Shape1.setTextureSize(1024, 512);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 55, 500);
      Shape2.addBox(0.5F, 0F, -0.5F, 1, 11, 1);
      Shape2.setRotationPoint(-1F, 12F, 0F);
      Shape2.setTextureSize(1024, 512);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 500);
      Shape3.addBox(0.5F, 0F, -0.5F, 3, 1, 3);
      Shape3.setRotationPoint(-2F, 11F, -1F);
      Shape3.setTextureSize(1024, 512);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 460);
      Shape4.addBox(0.5F, 0F, -0.5F, 1, 4, 1);
      Shape4.setRotationPoint(-1F, 12F, -1F);
      Shape4.setTextureSize(1024, 512);
      Shape4.mirror = true;
      setRotation(Shape4, 0.2230798F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 460);
      Shape5.addBox(0.5F, 0F, -0.5F, 1, 4, 1);
      Shape5.setRotationPoint(-1F, 12F, 1F);
      Shape5.setTextureSize(1024, 512);
      Shape5.mirror = true;
      setRotation(Shape5, -0.223088F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 0, 460);
      Shape6.addBox(0.5F, 0F, -0.5F, 1, 4, 1);
      Shape6.setRotationPoint(0F, 12F, 0F);
      Shape6.setTextureSize(1024, 512);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0.223088F);
      Shape7 = new ModelRenderer(this, 0, 460);
      Shape7.addBox(0.5F, 0F, -0.5F, 1, 4, 1);
      Shape7.setRotationPoint(-2F, 12F, 0F);
      Shape7.setTextureSize(1024, 512);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, -0.223088F);
      Orb_of_doom = new ModelRenderer(this, 0, 0);
      Orb_of_doom.addBox(-0.5F, 0F, 0F, 450, 450, 0);
      Orb_of_doom.setRotationPoint(-220F, 450F, 0F);
      Orb_of_doom.setTextureSize(1024, 512);
      Orb_of_doom.mirror = true;
      setRotation(Orb_of_doom, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Orb_of_doom.render(f5 / 80);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
