// Date: 9/28/2013 2:16:01 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package assets.bigmod.textures.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Starfish extends ModelBase
{
    //fields
    ModelRenderer mid;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer Shape1;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer Shape2;

    public Starfish()
    {
        textureWidth = 64;
        textureHeight = 32;
        mid = new ModelRenderer(this, 4, 0);
        mid.addBox(0F, 0F, 0F, 3, 1, 3);
        mid.setRotationPoint(-2F, 23F, -1F);
        mid.setTextureSize(64, 32);
        mid.mirror = true;
        setRotation(mid, 0F, 0F, 0F);
        leg1 = new ModelRenderer(this, 0, 6);
        leg1.addBox(0F, 0F, 0F, 1, 1, 3);
        leg1.setRotationPoint(1F, 23F, 0F);
        leg1.setTextureSize(64, 32);
        leg1.mirror = true;
        setRotation(leg1, -0.260246F, 2.41661F, 0F);
        leg2 = new ModelRenderer(this, 0, 6);
        leg2.addBox(0F, 0F, 0F, 1, 1, 3);
        leg2.setRotationPoint(-2F, 23F, 1F);
        leg2.setTextureSize(64, 32);
        leg2.mirror = true;
        setRotation(leg2, -0.260246F, -0.7519374F, 0F);
        Shape1 = new ModelRenderer(this, 0, 6);
        Shape1.addBox(0F, 0F, 0F, 1, 1, 3);
        Shape1.setRotationPoint(-1F, 23F, 1F);
        Shape1.setTextureSize(64, 32);
        Shape1.mirror = true;
        setRotation(Shape1, -0.2974289F, -0.0371786F, 0F);
        leg3 = new ModelRenderer(this, 0, 6);
        leg3.addBox(0F, 0F, 0F, 1, 1, 3);
        leg3.setRotationPoint(0.4F, 23F, 2F);
        leg3.setTextureSize(64, 32);
        leg3.mirror = true;
        setRotation(leg3, -0.3346033F, 0.8922867F, 0F);
        leg4 = new ModelRenderer(this, 0, 6);
        leg4.addBox(0F, 0F, 0F, 1, 1, 3);
        leg4.setRotationPoint(-1F, 23F, -1F);
        leg4.setTextureSize(64, 32);
        leg4.mirror = true;
        setRotation(leg4, -0.3346033F, -2.390068F, 0F);
        Shape2 = new ModelRenderer(this, 0, 0);
        Shape2.addBox(0F, 0.7F, 0F, 1, 1, 1);
        Shape2.setRotationPoint(-1F, 22F, 0F);
        Shape2.setTextureSize(64, 32);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        mid.render(f5);
        leg1.render(f5);
        leg2.render(f5);
        Shape1.render(f5);
        leg3.render(f5);
        leg4.render(f5);
        Shape2.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity BOOOOGGER)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, BOOOOGGER);
    }
}
